version: '3'
services:
  strapi:
    container_name: gallery-strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'

  postgres:
    container_name: gallery-postgres
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  frontend-service:
    container_name: gallery-frontend
    image: node:14.15.0-alpine3.11
    command: tail -F /dev/null #  npm install && /bin/sh -c "npm start" 
    working_dir: /var/www/html
    volumes:
        - ./frontend:/var/www/html
    ports:
        - 3000:3000
    links:
        - strapi
    depends_on:
        - strapi