version: '3'
services:
  strapi:
    container_name: gallery-strapi
    image: strapi/strapi
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'
    volumes:
    - ./backend:/srv/app

  frontend-service:
    container_name: gallery-frontend
    image: node:14.15.0-alpine3.11
    command: tail -F /dev/null #  npm install && /bin/sh -c "npm start" 
    working_dir: /var/www/html
    volumes:
        - ./frontend:/var/www/html
    ports:
        - 3000:3000
    links:
        - strapi
    depends_on:
        - strapi